### ISSUE TITLE
adjustment of motors offsets

### ISSUE THREAD

**Issue by cholet852** [Red-Rabbit-Robotics/rx1#3]
Hello,

When I assembled the right arm I set all my motors to 2048 so that when initializing the right arm the starting position is correct (i.e. arm extended downwards).

the problem is that if I want to raise my arm upwards (with the second shoulder motor) it does not go very high because we exceed the authorized value range.

is there an adjustment to be made at the motor level with the feetech software other than the ids setup ?

**Comment by zlingkang** [comment]
For all the motors with extra 3D printed gearbox. Make their moving range minimum to be 0, and maximum to be 0 as well. This allows the original servo to make multiple turns (run beyond the range of 0 to 4096), so that when it’s geared down, it can still achieve full 360 degree motion

**Comment by cholet852** [comment]
hello, ok thanks for the information. I'm going to test this.

**Comment by cholet852** [comment]
I just made the changes and everything works perfectly again thank you.

I'm currently using ROS noetic in WSL2, but the performance is really bad. What are the capacities of the PC you used for Ubuntu 20.04 with Noetic? My goal for the moment being to be able to evaluate the position of an object and move it from point A to point B. (I have not yet purchased a lidar camera at the moment)

**Comment by zlingkang** [comment]
Glad it works! I am using a pretty moderate laptop, i7 cpu, 16G RAM, Nvidia 3090 (this repo shouldn't even really use any GPU, Instead of using WSL2, perhaps a native Ubuntu is better in general. 

When you talk about the "the performance is really bad", I suppose you meant the ik demo? The ik demo is an example of how to use this ik solver. In reality when you plan a trajectory for a robotic arm, you don't do ik for all the poses leading to the target location, instead, you only calculate the ik for the end target location once and then you plan a trajectory either using interpolation or more advanced techniques like RRT* or something like that with libraries like OMPL. (perhaps this is a separate topic and if you want, you can either comment in the redrabbitrobotics.cc website or open a separate issue in the relevant repo.)

**Comment by cholet852** [comment]
When I talk about performance, I talk about moving the camera in Rviz because of my PC of course. I'm installing a native Unbuntu on another PC. Thank you again for your work.

**Comment by zlingkang** [comment]
No problem man, hope it works out for you.
